"use client";

import React from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/sections/Footer';
import { BookOpen, Clock, Award, ShieldAlert, FileText, Mail, CheckCircle } from 'lucide-react';

const ExaminationPolicy = () => {
  const lastUpdated = "October 24, 2023";

  return (
    <main className="min-h-screen bg-[#020617] text-slate-100 font-sans">
      <Navbar />

      <section className="pt-32 pb-16 px-6 border-b border-white/5 bg-slate-900/20">
        <div className="max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 mb-6 backdrop-blur-xl">
            <BookOpen size={14} className="text-blue-400" />
            <span className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-200">Academic Integrity</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase italic mb-4">
            Examination <span className="text-slate-500">Policy.</span>
          </h1>
          <p className="text-slate-400 font-light italic text-sm">Last Updated: {lastUpdated}</p>
        </div>
      </section>

      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto space-y-16">
          
          <article className="space-y-6">
            <div className="flex items-center gap-3 text-blue-400">
              <FileText size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">Assessment Standards</h2>
            </div>
            <p className="text-slate-400 leading-relaxed font-light">
              Our examination policy ensures a fair, consistent, and rigorous evaluation of all students. By participating in our assessments, you agree to adhere to the code of conduct and technical requirements outlined below. These standards are designed to maintain the prestige of our certifications.
            </p>
          </article>

          <article className="p-8 rounded-[2rem] bg-blue-500/5 border border-blue-500/20 space-y-6">
            <div className="flex items-center gap-3 text-red-400">
              <ShieldAlert size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">Code of Conduct</h2>
            </div>
            <div className="space-y-4 text-slate-400 leading-relaxed font-light">
              <p>
                Academic honesty is paramount. The following actions are strictly prohibited during any examination:
              </p>
              <ul className="list-disc pl-6 space-y-3 marker:text-blue-500">
                <li><strong>Plagiarism:</strong> Submission of work that is not entirely your own or generated by unauthorized AI tools.</li>
                <li><strong>Collaboration:</strong> Communicating with other candidates or external parties during live assessments.</li>
                <li><strong>External Materials:</strong> Using unauthorized books, notes, or digital resources unless explicitly permitted.</li>
                <li><strong>Violation:</strong> Any breach of these rules may lead to immediate disqualification without a refund.</li>
              </ul>
            </div>
          </article>

          <article className="space-y-6">
            <div className="flex items-center gap-3 text-blue-400">
              <Clock size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">Technical Requirements</h2>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/5">
                <h4 className="text-white font-bold text-sm mb-2 uppercase italic tracking-wider">System Stability</h4>
                <p className="text-xs text-slate-500 leading-relaxed">Ensure a stable internet connection. We are not responsible for progress lost due to local hardware or network failures.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/5">
                <h4 className="text-white font-bold text-sm mb-2 uppercase italic tracking-wider">Timed Sessions</h4>
                <p className="text-xs text-slate-500 leading-relaxed">Exams must be completed within the allotted time. Once the timer expires, your current progress will be auto-submitted.</p>
              </div>
            </div>
          </article>

          <article className="space-y-6">
            <div className="flex items-center gap-3 text-blue-400">
              <Award size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">Passing Criteria & Results</h2>
            </div>
            <div className="space-y-4 text-slate-400 leading-relaxed font-light">
               <p className="flex items-center gap-2">
                 <CheckCircle size={14} className="text-blue-500" /> 
                 Minimum passing score is **70%** unless stated otherwise.
               </p>
               <p className="flex items-center gap-2">
                 <CheckCircle size={14} className="text-blue-500" /> 
                 Results are typically processed and released within **3 to 5 business days**.
               </p>
               <p className="flex items-center gap-2">
                 <CheckCircle size={14} className="text-blue-500" /> 
                 Retake opportunities are subject to a mandatory 7-day cooling-off period.
               </p>
            </div>
          </article>

          <article className="pt-10 border-t border-white/5">
            <div className="flex flex-col md:flex-row justify-between gap-10">
              <div className="space-y-4 max-w-sm">
                <div className="flex items-center gap-2 text-white font-black italic uppercase">
                  <Mail size={16} />
                  <span>Exam Registrar</span>
                </div>
                <p className="text-sm text-slate-500 font-light">
                  For technical issues during an exam or to appeal a grading decision, please contact our academic board.
                </p>
              </div>
              <div className="space-y-4">
                <h3 className="text-white font-black italic uppercase tracking-tighter text-2xl">Dispute?</h3>
                <p className="text-slate-400 text-sm mb-4">Submit an appeal request via email:</p>
                <button 
                  onClick={() => window.location.href = 'mailto:exams@yourdomain.com'}
                  className="bg-white text-black px-8 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-blue-400 transition-all"
                >
                  Contact Registrar
                </button>
              </div>
            </div>
          </article>

        </div>
      </section>

      <Footer />
    </main>
  );
};

export default ExaminationPolicy;